### ISSUE TITLE
Homebrew hooks don't exist anymore?

### ISSUE THREAD

**Issue by bkeroackdsc** [jacob-meacham/brew-github-bottles#1]
It appears that `Homebrew::Hooks` doesn't exist any longer, unfortunately.

**Comment by jacob-meacham** [comment]
@bkeroackdsc thanks for flagging! Unfortunately, I don't use this plugin anymore and so haven't kept it updated. The Homebrew API looks like it's sufficiently changed to make updating the plugin difficult. If you want to take a stab at it, you're welcome to of course - otherwise, I'll add a deprecation warning.
